server:
  port: ${PORT:8080}


spring:
  datasource:
    username: ${USERNAME}
    password: ${PASSWORD}
    url: ${URL}

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

#server.max-http-header-size=700000000000000000
#  spring.resources.chain.strategy.content.enabled=true
#  spring.resources.chain.strategy.content.paths=/**
